language: node_js
node_js:
  - "9"
dist: trusty
sudo: false

branches:
  only:
    - master

cache:
  directories:
    - node_modules

install:
  - npm install

script:
  - npm run lint
  - ng build --prod --base-href /yacovi-web/
  - mv dist/yacovi-web/index.html dist/yacovi-web/404.html
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: dist/yacovi-web
  on:
    branch: master
